server:
  port: 8080
spring:
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:todolist # 連接位址
    driver-class-name: org.h2.Driver # 配置 driver
    username: sa # database 用戶名
    password: # database 密碼

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
