spring:
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://192.168.0.116:3306/todo # Docker in the VM
    username: todoUser
    password: todo123
    driver-class-name: com.mysql.cj.jdbc.Driver
